### ISSUE TITLE
Shader nodes bug when I have Cycles render view on.

### ISSUE THREAD

**Issue by genesis2303** [williamchange/node_tabber#10]
When I try to use ctrl+a in shader editor which is my default shortcut for node tabber while my viewport is using cycles I get this error (Blender 4.3.1):

Python: Traceback (most recent call last):
  File "/home/Gamer/.config/blender/4.3/scripts/addons/Node Tabber/operators.py", line 76, in invoke
    self.define_items(context)
  File "/home/Gamer/.config/blender/4.3/scripts/addons/Node Tabber/operators.py", line 15, in wrapped_func
    output = function(self, context)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Gamer/.config/blender/4.3/scripts/addons/Node Tabber/operators.py", line 46, in define_items
    items = nodelists.generate_entries(context, editor_type=tree_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Gamer/.config/blender/4.3/scripts/addons/Node Tabber/nodelists/__init__.py", line 303, in generate_entries
    entries.extend(generate_custom_node_entries(context))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Gamer/.config/blender/4.3/scripts/addons/Node Tabber/nodelists/__init__.py", line 85, in generate_custom_node_entries
    custom_node_entries = [
                          ^
  File "/home/Gamer/.config/blender/4.3/scripts/addons/Node Tabber/nodelists/__init__.py", line 85, in <listcomp>
    custom_node_entries = [
                          ^
  File "/home/Gamer/Blender Versions/daily/blender-4.3.1-stable+daily.33d812126174/4.3/scripts/modules/nodeitems_utils.py", line 142, in node_items_iter
    for item in cat.items(context):
  File "/home/Gamer/Blender Versions/daily/blender-4.3.1-stable+daily.33d812126174/4.3/scripts/modules/nodeitems_utils.py", line 25, in items_gen
    if item.poll is None or context is None or item.poll(context):
       ^^^^^^^^^
AttributeError: 'str' object has no attribute 'poll'

**Comment by Quackarooni** [comment]
Can't exactly reproduce the bug, Cycles works fine when I test is on my end.
https://github.com/user-attachments/assets/741dbbd4-4aea-4594-b7f7-c337d4fa6b01

The error log you posted is showing the code for reading custom node entries, so I'm suspecting you might have an addon that adds those when Cycles is enabled, and something about its implementation is causing an error.
*(For reference, custom node entries refer to nodes created via Python, example of an addon that does this is [FxNodes](<https://cgonfire.gumroad.com/l/fxnodes>))*

The part of the code that is erroring out is not Node Tabber's, but rather `nodeitems_utils.py`, which is a native Blender library. It hasn't been updated since Blender stopped using it for internal purposes, so it's largely just addons that hook into that.

To see if that really is the issue though, I'd like to ask you to disable this setting in the preferences and see whether that fixes things:
![image](https://github.com/user-attachments/assets/6144f79f-6c8a-41d7-914c-7e0f2154141e)
Other than that, the best Node Tabber could prolly do is to add a condition that ignores `nodeitems_utils.py` if it errors out, so I might do that on the next update.

**Comment by genesis2303** [comment]
Oh so Noise Nodes causing this, than you. I'd probably wouldn't though about this one and try to turn off other 30+ add-ons first.
